[package]
name = "rocket"
description = "Search program for adapting 3D Rubik's cube algorithms to 4D efficiently via RKT"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
eframe = "0.27.2"
